name: Build All

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  call_revanced:
    uses: ./.github/workflows/build-revanced-youtube.yml
    secrets:
      REVANCED_KEYSTORE: ${{ secrets.REVANCED_KEYSTORE }}

  call_morphe:
    uses: ./.github/workflows/build-morphe-youtube.yml
    secrets:
      MORPHE_KEYSTORE: ${{ secrets.MORPHE_KEYSTORE }}

  call_reddit:
    uses: ./.github/workflows/build-morphe-reddit.yml
    secrets:
      MORPHE_KEYSTORE: ${{ secrets.MORPHE_KEYSTORE }}

  release:
    needs: [call_revanced, call_morphe, call_reddit]
    runs-on: windows-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v6

      - name: Download YouTube ReVanced artifact
        uses: actions/download-artifact@v7
        with:
          name: YouTube-ReVanced

      - name: Download YouTube Morphe artifact
        uses: actions/download-artifact@v7
        with:
          name: YouTube-Morphe

      - name: Download Reddit artifact
        uses: actions/download-artifact@v7
        with:
          name: Reddit

      - name: Create Release Notes
        id: release_notes
        run: |
          (Get-Content -Path ReleaseNotesTemplate.md -Encoding utf8 -Raw).
          replace("ZuluVersion", "${{ needs.call_revanced.outputs.zulu }}").
          replace("RevancedCli", "${{ needs.call_revanced.outputs.cli }}").
          replace("RevancedPatches", "${{ needs.call_revanced.outputs.patches }}").
          replace("RevancedYoutube", "${{ needs.call_revanced.outputs.youtube_app }}").
          replace("RevancedMicroG", "${{ needs.call_revanced.outputs.youtube_microg }}").
          replace("MorpheCli", "${{ needs.call_morphe.outputs.cli }}").
          replace("MorphePatches", "${{ needs.call_morphe.outputs.patches }}").
          replace("MorpheYoutube", "${{ needs.call_morphe.outputs.youtube_app }}").
          replace("MorpheMicroG", "${{ needs.call_morphe.outputs.youtube_microg }}").
          replace("RedditTag", "${{ needs.call_reddit.outputs.reddit_app }}") |
          Set-Content -Path ReleaseNotesTemplate.md -Encoding utf8 -Force

          Add-Content -Path $env:GITHUB_OUTPUT -Value "ReleaseBody=ReleaseNotesTemplate.md"

          $ReleaseName = Get-Date -f "yyyy.MM.dd"
          echo "RELEASE_NAME=$ReleaseName" >> $env:GITHUB_ENV

      - name: Upload to Releases
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ env.RELEASE_NAME }}
          body_path: ${{ steps.release_notes.outputs.ReleaseBody }}
          files: |
            Youtube-ReVanced.zip
            Youtube-Morphe.zip
            reddit.apk
